### ISSUE TITLE
VRAM: BUG when adding process

### ISSUE THREAD

**Issue by Darfeikus** [Darfeikus/Memorama#2]
Cuando se añade un nuevo proceso, se hace bien la verificación inicial, pero el metodo **storeInMemory** llena toda la memoria **VRAM** con ese proceso. 

![image](https://user-images.githubusercontent.com/32723476/88714906-119ee100-d0e3-11ea-97d0-2e84f3ace303.png)

Hay que llenarlo con la cantidad de bytes que se tienen en **addProcess**

**Comment by MiguelSilvaR** [comment]
Ajuste el método para que ahora haya un contador de páginas y no se siga en toda la memoria
